USE EbookManagement;

INSERT INTO Account(Username, Roles,Passwords , Fullname , email , phone) VALUES 
('user1' , 'Admin','12345' , 'Mr A', 'MrA@gmail.com', 12345678901)  ,
('user2' , 'User','12345' , 'Mr B', 'MrB@gmail.com', 12345678901)  ,
('user3' , 'User','12345' , 'Mr C', 'MrC@gmail.com', 12345678901) ,
('Khoa' , 'Admin','123456789' , 'Dong Bach Khoa', 'MrBachKhoa@gmail.com', 69696969)  ,
('BuPu' , 'User','123456' , 'Mr BuPu', 'MrBuPu@gmail.com', 12123)  ,
('JimmiBuh' , 'User','123456' , 'Mr Jimmi', 'JimmiBuh@gmail.com', 1678901)  ,
('NghiBuh' , 'User','123456' , 'Mr Nghi', 'MrNghi@gmail.com', 123456789), 
('XThanh' , 'User','123456' , 'Mr Thanh', 'MrThanh@gmail.com', 12345678910) ; 

INSERT INTO Book(BookName, BookCover, YearOfPublic, Summary , Languages , Content , UpdateDate  ) VALUES 
('Clean Code' , 'images/BookCovers/cleancode.png', 2008  ,'Even bad code can function. But if code isn''t clean, it can bring a development organization to its knees.','English','se.pdf', '2020-05-14'),
('Design Patterns: Elements of Reusable Object-Oriented Software', 'images/BookCovers/designpatterns.png',1994,'Design Patterns is a modern classic in the literature of object-oriented development','English','se.pdf', '2021-06-12'),
('The Pragmatic Programmer Your Journey To Mastery, 20th Anniversary Edition', 'images/BookCovers/thepragmaticprogrammer.png',2019,'To participate in the next generation of professional product delivery you have to be pragmatic but disciplined.' , 'English', 'se.pdf', '2019-07-19') ,
('Java: A Beginner''s Guide, Eighth Edition', 'images/BookCovers/javabeginner.png',2018,' Java: A Beginner''s Guide, Eighth Edition gets you started programming in Java right away.Best-selling programming author Herb Schildt begins with the basics, such as how to create, compile, and run a Java program','English','javabeginner.pdf', '2021-06-12'),
('Data Structures and Algorithms in Java', 'images/BookCovers/datastructures.png',2014,' Concrete data structures realizing the ADTs are provided as Java classes implementing the interfaces. The Java code implementing fundamental data structures in this book is organized in a single Java package, net.datastructures. This package forms a coherent library of data structures and algorithms in Java specifically designed for educational purposes in a way that is complimentary with the Java Collections Framework.','English','datastructures.pdf', '2022-07-12'),
('Python Crash Course, 2nd Edition', 'images/BookCovers/pythoncourse.png',2019,' You''ll begin with basic concepts like variables, lists, classes, and loops—with the help of fun skill-strengthening exercises for every topic—then move on to making interactive programs and best practices for testing your code. Later chapters put your new knowledge into play with three cool projects: a 2D Space Invaders-style arcade game, a set of responsive data visualizations you''ll build with Pythons handy libraries (Pygame, Matplotlib, Plotly, Django), and a customized web app you can deploy online.','English','datastructures.pdf', '2022-07-12'),
('Grokking Algorithms', 'images/BookCovers/grokking.png',2016,'Grokking Algorithms is a friendly guide that teaches you how to apply common algorithms to the practical problems you face every day as a programmer. You''ll start with sorting and searching and, as you build up your skills in thinking algorithmically, you''ll tackle more complex concerns such as data compression and artificial intelligence','English','se.pdf', '2022-07-12'),
('Smart thinking: Skills for critical understanding and writing' , 'images/BookCovers/smartthinking.png', 2013  ,'Smart Thinking: Skills for Critical Understanding and Writing 2e is a practical, step-by-step guide to improving skills in analysis, critical thinking, and the effective communication of arguments and explanations. The book combines an accessible and straightforward style, with a strong foundation of knowledge. ','English','se.pdf', '2022-07-13'),
('Give and Take: Why Helping Others Drives Our Success' , 'images/BookCovers/giveandtake.png', 2014  ,'For generations, we have focused on the individual drivers of success: passion, hard work, talent, and luck. But in today’s dramatically reconfigured world, success is increasingly dependent on how we interact with others. In Give and Take, Adam Grant, an award-winning researcher and Wharton’s highest-rated professor, examines the surprising forces that shape why some people rise to the top of the success ladder while others sink to the bottom. Praised by social scientists, business theorists, and corporate leaders, Give and Take opens up an approach to work, interactions, and productivity that is nothing short of revolutionary.','English','se.pdf', '2022-07-14'),
('Power Up Your Mind: Learn Faster, Work Smarter' , 'images/BookCovers/powerup.png', 2001,'Bill Lucas, a leading international expert on life-long learning, shows that while we have learned more about how the brain works in the last decade than we have ever known, only a fraction of this is grasped and applied by most people. Power Up Your Mind applies this practical knowledge for the first time and shows you how to learn.','English','se.pdf', '2020-07-14'),
('The Alchemist' , 'images/BookCovers/powerup.png', 2014  ,'Paulo Coelho''s enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried near the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself king, and an alchemist, all of whom point Santiago in the direction of his quest. No one knows what the treasure is, or if Santiago will be able to surmount the obstacles in his path.','English','thealchemist.pdf', '2022-07-14'),
('Rich Dad Poor Dad' , 'images/BookCovers/richdadpoordad.png', 2017  ,'Rich Dad Poor Dad is Robert''s story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.','English','richdadpoordad.pdf', '2022-07-14'),
('How To Win Friends And Influence People' , 'images/BookCovers/howto.png', 1936  ,'The 1981 edition of How to Win Friends and Influence People is broken into the following parts: "Twelve Things This Book Will Do For You", "Fundamental Techniques in Handling People", "Twelve Ways to Win People to Your Way of Thinking", and "Be a Leader: How to Change People Without Giving Offense or Arousing Resentment". The 1936 edition also contained "Letters That Produced Miraculous Results" and "Seven Rules for Making Your Home Life Happier".','English','towin.pdf', '2022-07-14'),
('To Kill Mockingbird' , 'images/BookCovers/tokill.png', 2010  ,'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.','English','tokill.pdf', '2022-07-14'),
('Animal Farm' , 'images/BookCovers/animalfarm.png', 1945  ,'Mr Jones of Manor Farm is so lazy and drunken that one day he forgets to feed his livestock. The ensuing rebellion under the leadership of the pigs Napoleon and Snowball leads to the animals taking over the farm. Vowing to eliminate the terrible inequities of the farmyard, the renamed Animal Farm is organised to benefit all who walk on four legs. But as time passes, the ideals of the rebellion are corrupted, then forgotten. And something new and unexpected emerges.','English','animalfarm.pdf', '2022-07-15'),
('Emotional Intelligence' , 'images/BookCovers/emotional.png', 1995  , 'Goleman posits that emotional intelligence is as important as IQ for success, including in academic, professional, social, and interpersonal aspects of one''s life. Goleman says that emotional intelligence is a skill that can be taught and cultivated, and outlines methods for incorporating emotional skills training in school curriculum','English','se.pdf', '2022-07-16');

INSERT INTO Author(AuthorName , Profiles) VALUES 
('Robert C.Martin','founder and president of Object Mentor, Inc., a team of experienced consultants who mentor their clients worldwide in the fields of C++, Java, C#, Ruby, OO, Design Patterns, UML, Agile Methodologies, and eXtreme programming.'),
('Erich Gamma' , 'Swiss computer scientist and co-author of the influential software engineering textbook, Design Patterns: Elements of Reusable Object-Oriented Software. He co-wrote the JUnit software testing framework with Kent Beck and led the design of the Eclipse platforms Java Development Tools'),
('Andy Hunt' ,'an author and publisher. Hes authored and co-authored the best-selling classic The Pragmatic Programmer, the popular Pragmatic Thinking & Learning, award-winning Practices of an Agile Developer, Learn to Program with Minecraft Plugins: Create Flying Creepers and Flaming Cows in Java for the kids, many articles, and the novels in the Conglommora series. Andy was one of the 17 authors of the Agile Manifesto' ),
('Kevin Kelly' ,'Kevin Kelly (born 1952) is the founding executive editor of Wired magazine, and a former editor/publisher of the Whole Earth Review. He has also been a writer, photographer, conservationist, and student of Asian and digital culture.' ),
('Alec Ross' ,' is an American technology policy expert who was Senior Advisor for Innovation to Secretary of State Hillary Clinton for the duration of her term as Secretary of State.After leaving the Department of State in 2013 he joined the School of International and Public Affairs, Columbia University as a Senior Fellow' );


INSERT INTO Subjects(SubName,majorID ) VALUES ('DiscreteMath', '1') , ('AdvancedMath','1') , ('ProMath','1'), ('JavaBeginner','2')
, ('JavaAdvanced','2'), ('BeginnerC','2') , ('AdvancedC','2') , ('BeginnerEnglish', '3') , ('AdvancedEnglish' ,'3') , ('PMath','3') ; 

INSERT INTO ManageBook(UpdateDate) VALUES 
('2019-07-19'),('2022-05-08') ,('2019-11-15')  ;

Insert into ReadingHistory(DateRead , UserID , BookID , DeleteStatus) Values ('20220608 10:34:09 AM',1,1,0) ; 

INSERT INTO Major(MajorName) VALUES 
('Computer science') , ('Mathematics') , ('other') ;  

INSERT INTO BookRating(Daterating ,NoOfRate ,CmtContent) VALUES 
('2019-01-12', 42 , 'some thing funny'),('2021-08-05' , 11 , 'ya ya') ,('2019-11-15',12 ,'blah blah')  ;
